// 登录日志列表
const loginLogList = [
  {
    id: '198702',
    username: 'developer',
    nickname: '张三',
    ipAddr: '202.106.86.132',
    loginLoc: '江西省 南昌市',
    browser: 'Chrome 11',
    os: 'Windows 10',
    status: '1',
    msg: '登录成功',
    loginTime: '2023-11-24 11:26:01',
  },
  {
    id: '198701',
    username: 'admin',
    nickname: '周大帅',
    ipAddr: '114.240.77.242',
    loginLoc: '北京市 北京市',
    browser: 'Chrome 11',
    os: 'Windows 10',
    status: '1',
    msg: '登录成功',
    loginTime: '2023-11-24 11:26:14',
  },
  {
    id: '198700',
    username: 'admin',
    nickname: '周大帅',
    ipAddr: '114.240.77.242',
    loginLoc: '北京市 北京市',
    browser: 'Chrome 11',
    os: 'Windows 10',
    status: '1',
    msg: '登录成功',
    loginTime: '2023-11-24 11:26:14',
  },
  {
    id: '198699',
    username: 'admin',
    nickname: '周大帅',
    ipAddr: '114.249.214.193',
    loginLoc: '北京市 北京市',
    browser: 'Chrome 11',
    os: 'Windows 10',
    status: '0',
    msg: '登录失败',
    loginTime: '2023-11-24 11:26:06',
  },
  {
    id: '198698',
    username: 'admin',
    nickname: '周大帅',
    ipAddr: '114.240.77.242',
    loginLoc: '北京市 北京市',
    browser: 'Chrome 11',
    os: 'Windows 10',
    status: '1',
    msg: '登录成功',
    loginTime: '2023-11-24 11:26:14',
  },
  {
    id: '198697',
    username: 'admin',
    nickname: '周大帅',
    ipAddr: '114.249.214.193',
    loginLoc: '北京市 北京市',
    browser: 'Chrome 11',
    os: 'Windows 10',
    status: '0',
    msg: '登录失败',
    loginTime: '2023-11-24 11:26:06',
  },
  {
    id: '198696',
    username: 'developer',
    nickname: '张三',
    ipAddr: '202.106.86.132',
    loginLoc: '江西省 南昌市',
    browser: 'Chrome 11',
    os: 'Windows 10',
    status: '1',
    msg: '登录成功',
    loginTime: '2023-11-24 11:26:01',
  },
  {
    id: '198695',
    username: 'admin',
    nickname: '周大帅',
    ipAddr: '202.106.86.147',
    loginLoc: '江西省 宜春市',
    browser: 'Chrome 12',
    os: 'Windows 11',
    status: '0',
    msg: '登录失败',
    loginTime: '2023-12-24 11:26:01',
  },
  {
    id: '198694',
    username: 'admin',
    nickname: '周大帅',
    ipAddr: '202.106.86.147',
    loginLoc: '江西省 宜春市',
    browser: 'Chrome 12',
    os: 'Windows 11',
    status: '0',
    msg: '登录失败',
    loginTime: '2023-12-24 11:26:01',
  },
  {
    id: '198693',
    username: 'admin',
    nickname: '周大帅',
    ipAddr: '114.240.77.242',
    loginLoc: '北京市 北京市',
    browser: 'Chrome 11',
    os: 'Windows 10',
    status: '1',
    msg: '登录成功',
    loginTime: '2023-11-24 11:26:14',
  },
  {
    id: '198692',
    username: 'admin',
    nickname: '周大帅',
    ipAddr: '114.249.214.193',
    loginLoc: '北京市 北京市',
    browser: 'Chrome 11',
    os: 'Windows 10',
    status: '0',
    msg: '登录失败',
    loginTime: '2023-11-24 11:26:06',
  },
  {
    id: '198691',
    username: 'developer',
    nickname: '张三',
    ipAddr: '202.106.86.132',
    loginLoc: '江西省 南昌市',
    browser: 'Chrome 11',
    os: 'Windows 10',
    status: '1',
    msg: '登录成功',
    loginTime: '2023-11-24 11:26:01',
  }
]

// 操作日志列表
const operLogList = [
  {
    id: '5503',
    title: '代码生成',
    operType: '8',
    operName: 'admin',
    operIp: '222.128.15.208',
    operLoc: '北京市 北京市',
    costTime: 16,
    status: '0',
    operTime: '2023-11-24 09:55:36',
    operUrl: '/tool/gen/batchGenCode',
    reqMethod: 'GET',
    operMethod: 'com.zs.project.tool.gen.controller.GenController.batchGenCode()',
    operParam: '{"tables":"sys_post"}',
    jsonResult: '',
    errorMsg: ''
  },
  {
    id: '5502',
    title: '代码生成',
    operType: '8',
    operName: 'admin',
    operIp: '222.128.15.208',
    operLoc: '北京市 北京市',
    costTime: 16,
    status: '0',
    operTime: '2023-11-24 09:55:36',
    operUrl: '/tool/gen/batchGenCode',
    reqMethod: 'GET',
    operMethod: 'com.zs.project.tool.gen.controller.GenController.batchGenCode()',
    operParam: '{"tables":"sys_post"}',
    jsonResult: '',
    errorMsg: ''
  },
  {
    id: '5501',
    title: '代码生成',
    operType: '8',
    operName: 'admin',
    operIp: '222.128.15.208',
    operLoc: '北京市 北京市',
    costTime: 16,
    status: '0',
    operTime: '2023-11-24 09:55:36',
    operUrl: '/tool/gen/batchGenCode',
    reqMethod: 'GET',
    operMethod: 'com.zs.project.tool.gen.controller.GenController.batchGenCode()',
    operParam: '{"tables":"sys_post"}',
    jsonResult: '',
    errorMsg: ''
  },
  {
    id: '5500',
    title: '代码生成',
    operType: '8',
    operName: 'admin',
    operIp: '222.128.15.208',
    operLoc: '北京市 北京市',
    costTime: 16,
    status: '0',
    operTime: '2023-11-24 09:55:36',
    operUrl: '/tool/gen/batchGenCode',
    reqMethod: 'GET',
    operMethod: 'com.zs.project.tool.gen.controller.GenController.batchGenCode()',
    operParam: '{"tables":"sys_post"}',
    jsonResult: '',
    errorMsg: ''
  },
  {
    id: '5499',
    title: '代码生成',
    operType: '8',
    operName: 'admin',
    operIp: '116.128.245.109',
    operLoc: '湖南省 长沙市',
    costTime: 16,
    status: '1',
    operTime: '2023-11-24 10:00:59',
    operUrl: '/tool/gen/batchGenCode',
    reqMethod: 'GET',
    operMethod: 'com.ruoyi.project.tool.gen.controller.GenController.batchGenCode()',
    operParam: '{"tables":"sys_post"}',
    jsonResult: '',
    errorMsg: ''
  },
  {
    id: '5498',
    title: '代码生成',
    operType: '8',
    operName: 'admin',
    operIp: '59.49.17.59',
    operLoc: '山西省 太原市',
    costTime: 15,
    status: '1',
    operTime: '2023-11-24 09:56:03',
    operUrl: '/tool/gen/batchGenCode',
    reqMethod: 'GET',
    operMethod: 'com.zs.project.tool.gen.controller.GenController.batchGenCode()',
    operParam: '{"tables":"sys_post"}',
    jsonResult: '',
    errorMsg: ''
  },
  {
    id: '5497',
    title: '代码生成',
    operType: '8',
    operName: 'admin',
    operIp: '222.128.15.208',
    operLoc: '北京市 北京市',
    costTime: 16,
    status: '0',
    operTime: '2023-11-24 09:55:36',
    operUrl: '/tool/gen/batchGenCode',
    reqMethod: 'GET',
    operMethod: 'com.zs.project.tool.gen.controller.GenController.batchGenCode()',
    operParam: '{"tables":"sys_post"}',
    jsonResult: '',
    errorMsg: ''
  },
  {
    id: '5496',
    title: '代码生成',
    operType: '8',
    operName: 'admin',
    operIp: '222.128.15.208',
    operLoc: '北京市 北京市',
    costTime: 16,
    status: '0',
    operTime: '2023-11-24 09:55:36',
    operUrl: '/tool/gen/batchGenCode',
    reqMethod: 'GET',
    operMethod: 'com.zs.project.tool.gen.controller.GenController.batchGenCode()',
    operParam: '{"tables":"sys_post"}',
    jsonResult: '',
    errorMsg: ''
  },
  {
    id: '5495',
    title: '代码生成',
    operType: '8',
    operName: 'admin',
    operIp: '222.128.15.208',
    operLoc: '北京市 北京市',
    costTime: 16,
    status: '0',
    operTime: '2023-11-24 09:55:36',
    operUrl: '/tool/gen/batchGenCode',
    reqMethod: 'GET',
    operMethod: 'com.zs.project.tool.gen.controller.GenController.batchGenCode()',
    operParam: '{"tables":"sys_post"}',
    jsonResult: '',
    errorMsg: ''
  },
  {
    id: '5494',
    title: '代码生成',
    operType: '8',
    operName: 'admin',
    operIp: '222.128.15.208',
    operLoc: '北京市 北京市',
    costTime: 16,
    status: '0',
    operTime: '2023-11-24 09:55:36',
    operUrl: '/tool/gen/batchGenCode',
    reqMethod: 'GET',
    operMethod: 'com.zs.project.tool.gen.controller.GenController.batchGenCode()',
    operParam: '{"tables":"sys_post"}',
    jsonResult: '',
    errorMsg: ''
  },
  {
    id: '5493',
    title: '代码生成',
    operType: '8',
    operName: 'admin',
    operIp: '222.128.15.208',
    operLoc: '北京市 北京市',
    costTime: 16,
    status: '0',
    operTime: '2023-11-24 09:55:36',
    operUrl: '/tool/gen/batchGenCode',
    reqMethod: 'GET',
    operMethod: 'com.zs.project.tool.gen.controller.GenController.batchGenCode()',
    operParam: '{"tables":"sys_post"}',
    jsonResult: '',
    errorMsg: ''
  },
  {
    id: '5492',
    title: '代码生成',
    operType: '8',
    operName: 'admin',
    operIp: '222.128.15.208',
    operLoc: '北京市 北京市',
    costTime: 16,
    status: '0',
    operTime: '2023-11-24 09:55:36',
    operUrl: '/tool/gen/batchGenCode',
    reqMethod: 'GET',
    operMethod: 'com.zs.project.tool.gen.controller.GenController.batchGenCode()',
    operParam: '{"tables":"sys_post"}',
    jsonResult: '',
    errorMsg: ''
  },
  {
    id: '5491',
    title: '代码生成',
    operType: '8',
    operName: 'admin',
    operIp: '222.128.15.208',
    operLoc: '北京市 北京市',
    costTime: 16,
    status: '0',
    operTime: '2023-11-24 09:55:36',
    operUrl: '/tool/gen/batchGenCode',
    reqMethod: 'GET',
    operMethod: 'com.zs.project.tool.gen.controller.GenController.batchGenCode()',
    operParam: '{"tables":"sys_post"}',
    jsonResult: '',
    errorMsg: ''
  },
]

// 错误日志列表
const errorLogList = [

]

export {
  loginLogList,
  operLogList,
  errorLogList
}