const menuItemObj = {
  parentId: '0',
  parentTitle: null,
  id: '',
  sort: 1,
  type: 'directory',
  title: '',
  icon: '',
  iconSize: '20px',
  isLink: '0',
  path: '',
  name: '',
  component: null,
  perms: '',
  isCache: '1',
  isVisible: '1',
  isClearable: '1',
  status: '1',
  children: [],
  creator: '超级管理员',
  createTime: '2023-11-13 17:08:36'
}

// 深拷贝
const deepCopy = function (obj) {
  return JSON.parse(JSON.stringify(obj))
}

// 所有菜单列表
const menuListAll = [
  // 首页 --------------------------------------------------------------------------------------------------------------------------------------------------
  Object.assign(deepCopy(menuItemObj), {
    id: '99',
    sort: 1,
    type: 'menu',
    title: '首页',
    icon: 'home1',
    iconSize: '18px',
    path: 'home',
    name: 'home',
    component: 'backstage-pages/home/home',
    perms: 'home:manage',
  }),
  // 控制台菜单 --------------------------------------------------------------------------------------------------------------------------------------------
  Object.assign(deepCopy(menuItemObj), {
    id: '1',
    sort: 10,
    title: '控制台',
    icon: 'console1',
    iconSize: '18px',
    path: 'dashboard',
    name: 'dashboard',
    perms: 'dashboard:manage',
    children: [
      Object.assign(deepCopy(menuItemObj), {
        parentId: '1',
        parentTitle: '控制台',
        id: '11',
        sort: 10,
        type: 'menu',
        title: '工作台',
        icon: 'work1',
        iconSize: '16px',
        path: 'dashboard/workbenches',
        name: 'dashboard:workbenches',
        component: 'backstage-pages/dashboard/workbenches/workbenches',
        perms: 'dashboard:workbenches:page',
      }),
      Object.assign(deepCopy(menuItemObj), {
        parentId: '1',
        parentTitle: '控制台',
        id: '12',
        sort: 20,
        type: 'menu',
        title: '监控台',
        icon: 'monitor1',
        iconSize: '16px',
        path: 'dashboard/monitor',
        name: 'dashboard:monitor',
        component: 'backstage-pages/dashboard/monitor/monitor',
        perms: 'dashboard:monitor:page',
      }),
      Object.assign(deepCopy(menuItemObj), {
        parentId: '1',
        parentTitle: '控制台',
        id: '13',
        sort: 30,
        type: 'menu',
        title: '分析台',
        icon: 'analysis1',
        path: 'dashboard/analysis',
        name: 'dashboard:analysis',
        component: 'backstage-pages/dashboard/analysis/analysis',
        perms: 'dashboard:analysis:page',
      })
    ]
  }),
  // 系统管理菜单 -------------------------------------------------------------------------------------------------------------------------------------------------
  Object.assign(deepCopy(menuItemObj), {
    id: '2',
    sort: 20,
    title: '系统管理',
    icon: 'system1',
    path: 'system',
    name: 'system',
    perms: 'system:manage',
    children: [
      Object.assign(deepCopy(menuItemObj), {
        parentId: '2',
        parentTitle: '系统管理',
        id: '21',
        sort: 10,
        type: 'menu',
        title: '菜单管理',
        icon: 'menu3',
        path: 'system/menu',
        name: 'system:menu',
        component: 'backstage-pages/system/menu/menu',
        perms: 'system:menu:page',
      }),
      Object.assign(deepCopy(menuItemObj), {
        parentId: '2',
        parentTitle: '系统管理',
        id: '22',
        sort: 20,
        type: 'menu',
        title: '角色管理',
        icon: 'role1',
        path: 'system/role',
        name: 'system:role',
        component: 'backstage-pages/system/role/role',
        perms: 'system:role:page',
      }),
      Object.assign(deepCopy(menuItemObj), {
        parentId: '2',
        parentTitle: '系统管理',
        id: '23',
        sort: 30,
        type: 'menu',
        title: '部门管理',
        icon: 'dept1',
        path: 'system/dept',
        name: 'system:dept',
        component: 'backstage-pages/system/dept/dept',
        perms: 'system:dept:page',
      }),
      Object.assign(deepCopy(menuItemObj), {
        parentId: '2',
        parentTitle: '系统管理',
        id: '24',
        sort: 40,
        type: 'menu',
        title: '岗位管理',
        icon: 'post1',
        path: 'system/post',
        name: 'system:post',
        component: 'backstage-pages/system/post/post',
        perms: 'system:post:page',
      }),
      Object.assign(deepCopy(menuItemObj), {
        parentId: '2',
        parentTitle: '系统管理',
        id: '25',
        sort: 50,
        type: 'menu',
        title: '用户管理',
        icon: 'user1',
        path: 'system/user',
        name: 'system:user',
        component: 'backstage-pages/system/user/user',
        perms: 'system:user:page',
      }),
      Object.assign(deepCopy(menuItemObj), {
        parentId: '2',
        parentTitle: '系统管理',
        id: '26',
        sort: 60,
        type: 'menu',
        title: '字典管理',
        icon: 'dict1',
        path: 'system/dict',
        name: 'system:dict',
        component: 'backstage-pages/system/dict/dict',
        perms: 'system:dict:page',
      }),
      Object.assign(deepCopy(menuItemObj), {
        parentId: '2',
        parentTitle: '系统管理',
        id: '27',
        sort: 70,
        type: 'menu',
        title: '参数管理',
        icon: 'param1',
        iconSize: '16px',
        path: 'system/param',
        name: 'system:param',
        component: 'backstage-pages/system/param/param',
        perms: 'system:param:page',
      }),
      Object.assign(deepCopy(menuItemObj), {
        parentId: '2',
        parentTitle: '系统管理',
        id: '28',
        sort: 80,
        type: 'menu',
        title: '通知公告',
        icon: 'notice1',
        path: 'system/notice',
        name: 'system:notice',
        component: 'backstage-pages/system/notice/notice',
        perms: 'system:notice:page',
      }),
      Object.assign(deepCopy(menuItemObj), {
        parentId: '2',
        parentTitle: '系统管理',
        id: '30',
        sort: 100,
        type: 'directory',
        title: '日志管理',
        icon: 'log1',
        iconSize: '16px',
        path: 'system/log',
        name: 'system:log',
        perms: 'system:log',
        children: [
          Object.assign(deepCopy(menuItemObj), {
            parentId: '30',
            parentTitle: '日志管理',
            id: '301',
            sort: 10,
            type: 'menu',
            title: '登录日志',
            icon: 'loginlog1',
            iconSize: '18px',
            path: 'system/log/loginlog',
            name: 'system:log:loginlog',
            component: 'backstage-pages/system/log/loginlog/loginlog',
            perms: 'system:loginlog:page',
          }),
          Object.assign(deepCopy(menuItemObj), {
            parentId: '30',
            parentTitle: '日志管理',
            id: '302',
            sort: 20,
            type: 'menu',
            title: '操作日志',
            icon: 'operlog1',
            iconSize: '21px',
            path: 'system/log/operlog',
            name: 'system:log:operlog',
            component: 'backstage-pages/system/log/operlog/operlog',
            perms: 'system:operlog:page',
          }),
          Object.assign(deepCopy(menuItemObj), {
            parentId: '30',
            parentTitle: '日志管理',
            id: '303',
            sort: 30,
            type: 'menu',
            title: '错误日志',
            icon: 'errorlog1',
            iconSize: '16px',
            path: 'system/log/errorlog',
            name: 'system:log:errorlog',
            component: 'backstage-pages/system/log/errorlog/errorlog',
            perms: 'system:errorlog:page',
          }),
        ]
      })
    ]
  })
]

export default menuListAll